- name: Create OpenStack instance
  hosts: localhost
  gather_facts: no
  vars:
    instance_name: "my-instance"
    flavor: "ecs.2C.4096MB.40GB"
    image: "Centos7.6_1810_x64"
    network: "provider"
    key_name: "wanghongwei public key"
    security_groups: "default"
  tasks:
    - name: Create instance
      os_server:
        state: present
        wait: true
        name: "{{ instance_name }}"
        flavor: "{{ flavor }}"
        image: "{{ image }}"
        network: "{{ network }}"
        key_name: "{{ key_name }}"
        security_groups: "{{ security_groups }}"
      register: instance
    - name: Print instance details
      debug:
        var: instance
    - name: Set fact for instance IP
      set_fact:
        instance_ip: "{{ instance.openstack.public_v4 }}"
