- name: Install and configure Nginx, MySQL and PHP
  hosts: "{{ instance_ip }}"
  become: true
  gather_facts: yes
  tasks:
    - name: Install Nginx, MySQL and PHP
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - nginx
        - mysql-server
        - php-fpm

    - name: Configure Nginx
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      notify: Restart Nginx

    - name: Configure PHP
      template:
        src: php.ini.j2
        dest: /etc/php/7.0/fpm/php.ini
      notify: Restart PHP-FPM

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted

    - name: Restart PHP-FPM
      service:
        name: php7.0-fpm
        state: restarted
