- name: Install and configure Nginx, MySQL and PHP
  hosts: all
  become: true
  gather_facts: yes
  tasks:
    - name: Install Nginx, MariaDB and PHP
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - epel-release
        - nginx
        - mariadb-server
        - php-fpm

    - name: Configure Nginx
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      notify: Restart Nginx

    - name: Configure PHP
      template:
        src: php.ini.j2
        dest: /etc/php.ini
      notify: Restart PHP-FPM

    - name: Start Nginx
      service:
        name: nginx
        state: started
      tags:
        - nginx

    - name: Start MariaDB
      service:
        name: mariadb
        state: started
      tags:
        - mariadb

    - name: Start PHP-FPM
      service:
        name: php-fpm
        state: started
      tags:
        - php-fpm

    - name: Open port 80
      firewalld:
        port: 80/tcp
        permanent: true
        state: enabled
        immediate: true

    - name: Open port 443
      firewalld:
        port: 443/tcp
        permanent: true
        state: enabled
        immediate: true

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted

    - name: Restart MariaDB
      service:
        name: mariadb
        state: restarted

    - name: Restart PHP-FPM
      service:
        name: php-fpm
        state: restarted
